# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# File was automatically generated by automatic-ebuild-maker
# https://github.com/BlueManCZ/automatic-ebuild-maker

EAPI=8
inherit unpacker xdg

DESCRIPTION="Min is a fast, minimal browser that protects your privacy."
HOMEPAGE="https://minbrowser.github.io/min/"
SRC_URI="amd64? ( https://github.com/minbrowser/min/releases/download/v${PV}/min-${PV}-amd64.deb )
	arm64? ( https://github.com/minbrowser/min/releases/download/v${PV}/min-${PV}-arm64.deb )"

LICENSE="Apache-2.0"
SLOT="0"
KEYWORDS="-* amd64 ~arm64"
RESTRICT="bindist mirror"
IUSE="alsa doc libnotify"

RDEPEND="dev-lang/python
	dev-libs/libgcrypt
	dev-libs/nss
	libnotify? ( x11-libs/libnotify )
	sys-libs/glibc
	virtual/libudev
	x11-libs/gtk+:3
	x11-libs/libXScrnSaver
	x11-libs/libXtst
	x11-misc/xdg-utils
	sys-libs/libcap
	alsa? ( media-libs/alsa-lib )"

QA_PREBUILT="*"

S=${WORKDIR}

src_install() {
	cp -a . "${ED}" || die "cp failed"

	rm -r "${ED}/usr/share/doc/min" || die "rm failed"

	if use doc ; then
		dodoc -r "usr/share/doc/min/"* || die "dodoc failed"
	fi
}
